baseURL = 'https://quinton.io/'
languageCode = 'en-gb'
title = 'Logs from the Matrix'
rssLimit = 20
copyright = '2025 Michael Quinton'
minify = false

[Author]
  name = 'mikequinton'
  email = 'michael@quinton.io'

[permalinks]
  posts = '/:year/:month/:day/:filename'
  pages = '/:slug'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[outputs]
  home = ['html', 'json', 'rss']


[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "photos"
    name = "Photos"
    url = "/photos/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
