baseURL = 'https://quinton.io/'
languageCode = 'en-us'
title = 'Hugo Serial Programmer'
rssLimit = 20
copyright = '2021 Janne Kemppainen'
minify = false

[Author]
  name = 'sharadcodes'
  email = 'me@example.com'

[permalinks]
  posts = '/:year/:month/:day/:filename'
  pages = '/:slug'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[outputs]
  home = ['html', 'json', 'rss']


[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "photos"
    name = "Photos"
    url = "/photos/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
